In [1]:
from google.colab import files
uploaded = files.upload()

Saving Airbnb.db to Airbnb.db
Saving pokemon.db to pokemon.db
Saving titanic.db to titanic.db
Saving Workers.db to Workers.db

In [2]:
%load_ext sql

In [3]:
%%sql
sqlite:////content/Airbnb.db

'Connected: @/content/Airbnb.db'

In [10]:
%%sql
sqlite:////content/Workers.db

'Connected: @/content/Workers.db'

In [5]:
%%sql
sqlite:////content/pokemon.db

'Connected: @/content/pokemon.db'

In [6]:
%%sql
sqlite:////content/titanic.db

'Connected: @/content/titanic.db'

In [11]:
%%sql
select sqlite_version()

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('3.22.0',)]

In [8]:
%%sql
select name from sqlite_master where type='table' and name not like 'sqlite_%'

   sqlite:////content/Airbnb.db
   sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[('titanic',)]

In [9]:
%%sql
select *
from titanic

   sqlite:////content/Airbnb.db
   sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[(1, 1, 'Allen, Miss. Elisabeth Walton', 'female', '29', 0, 0, '24160', 211.3375, 'B5', 'S', '2', None, 'St Louis, MO'),
 (1, 1, 'Allison, Master. Hudson Trevor', 'male', '0.9167', 1, 2, '113781', 151.55, 'C22 C26', 'S', '11', None, 'Montreal, PQ / Chesterville, ON'),
 (1, 0, 'Allison, Miss. Helen Loraine', 'female', '2', 1, 2, '113781', 151.55, 'C22 C26', 'S', None, None, 'Montreal, PQ / Chesterville, ON'),
 (1, 0, 'Allison, Mr. Hudson Joshua Creighton', 'male', '30', 1, 2, '113781', 151.55, 'C22 C26', 'S', None, '135', 'Montreal, PQ / Chesterville, ON'),
 (1, 0, 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', 'female', '25', 1, 2, '113781', 151.55, 'C22 C26', 'S', None, None, 'Montreal, PQ / Chesterville, ON'),
 (1, 1, 'Anderson, Mr. Harry', 'male', '48', 0, 0, '19952', 26.55, 'E12', 'S', '3', None, 'New York, NY'),
 (1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female', '63', 1, 0, '13502', 77.9583, 'D7', 'S', '10', None, 'Hudson, NY'),
 (1, 0, 'Andrews, Mr. Thomas Jr', 'male', '39', 0, 0, '112050', 0.0, 'A36', 'S', None, None, 'Belfast, NI'),
 (1, 1, 'Appleton, Mrs. Edward Dale (Charlotte Lamson)', 'female', '53', 2, 0, '11769', 51.4792, 'C101', 'S', 'D', None, 'Bayside, Queens, NY'),
 (1, 0, 'Artagaveytia, Mr. Ramon', 'male', '71', 0, 0, 'PC 17609', 49.5042, None, 'C', None, '22', 'Montevideo, Uruguay'),
 (1, 0, 'Astor, Col. John Jacob', 'male', '47', 1, 0, 'PC 17757', 227.525, 'C62 C64', 'C', None, '124', 'New York, NY'),
 (1, 1, 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)', 'female', '18', 1, 0, 'PC 17757', 227.525, 'C62 C64', 'C', '4', None, 'New York, NY'),
 (1, 1, 'Aubart, Mme. Leontine Pauline', 'female', '24', 0, 0, 'PC 17477', 69.3, 'B35', 'C', '9', None, 'Paris, France'),
 (1, 1, 'Barber, Miss. Ellen "Nellie"', 'female', '26', 0, 0, '19877', 78.85, None, 'S', '6', None, None),
 (1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', '80', 0, 0, '27042', 30.0, 'A23', 'S', 'B', None, 'Hessle, Yorks'),
 (1, 0, 'Baumann, Mr. John D', 'male', None, 0, 0, 'PC 17318', 25.925, None, 'S', None, None, 'New York, NY'),
 (1, 0, 'Baxter, Mr. Quigg Edmond', 'male', '24', 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', None, None, 'Montreal, PQ'),
 (1, 1, 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'female', '50', 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', '6', None, 'Montreal, PQ'),
 (1, 1, 'Bazzani, Miss. Albina', 'female', '32', 0, 0, '11813', 76.2917, 'D15', 'C', '8', None, None),
 (1, 0, 'Beattie, Mr. Thomson', 'male', '36', 0, 0, '13050', 75.2417, 'C6', 'C', 'A', None, 'Winnipeg, MN'),
 (1, 1, 'Beckwith, Mr. Richard Leonard', 'male', '37', 1, 1, '11751', 52.5542, 'D35', 'S', '5', None, 'New York, NY'),
 (1, 1, 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)', 'female', '47', 1, 1, '11751', 52.5542, 'D35', 'S', '5', None, 'New York, NY'),
 (1, 1, 'Behr, Mr. Karl Howell', 'male', '26', 0, 0, '111369', 30.0, 'C148', 'C', '5', None, 'New York, NY'),
 (1, 1, 'Bidois, Miss. Rosalie', 'female', '42', 0, 0, 'PC 17757', 227.525, None, 'C', '4', None, None),
 (1, 1, 'Bird, Miss. Ellen', 'female', '29', 0, 0, 'PC 17483', 221.7792, 'C97', 'S', '8', None, None),
 (1, 0, 'Birnbaum, Mr. Jakob', 'male', '25', 0, 0, '13905', 26.0, None, 'C', None, '148', 'San Francisco, CA'),
 (1, 1, 'Bishop, Mr. Dickinson H', 'male', '25', 1, 0, '11967', 91.0792, 'B49', 'C', '7', None, 'Dowagiac, MI'),
 (1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', '19', 1, 0, '11967', 91.0792, 'B49', 'C', '7', None, 'Dowagiac, MI'),
 (1, 1, 'Bissette, Miss. Amelia', 'female', '35', 0, 0, 'PC 17760', 135.6333, 'C99', 'S', '8', None, None),
 (1, 1, 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'male', '28', 0, 0, '110564', 26.55, 'C52', 'S', 'D', None, 'Stockholm, Sweden / Washington, DC'),
 (1, 0, 'Blackwell, Mr. Stephen Weart', 'male', '45', 0, 0, '113784', 35.5, 'T', 'S', None, None, 'Trenton, NJ'),
 (1, 1, 'Blank, Mr. Henry', 'male', '40', 0, 0, '112277', 31.0, 'A31', 'C', '7', None, 'Glen Ridge, NJ'),
 (1, 1, 'Bonnell, Miss. Caroline', 'female', '30', 0, 0, '36928', 164.8667, 'C7', 'S', '8', None, 'Youngstown, OH'),
 (1, 1, 'Bonnell, Miss. Elizabeth', 'female', '58', 0, 0, '113783', 26.55, 'C103', 'S', '8', None, 'Birkdale, England Cleveland, Ohio'),
 (1, 0, 'Borebank, Mr. John James', 'male', '42', 0, 0, '110489', 26.55, 'D22', 'S', None, None, 'London / Winnipeg, MB'),
 (1, 1, 'Bowen, Miss. Grace Scott', 'female', '45', 0, 0, 'PC 17608', 262.375, None, 'C', '4', None, 'Cooperstown, NY'),
 (1, 1, 'Bowerman, Miss. Elsie Edith', 'female', '22', 0, 1, '113505', 55.0, 'E33', 'S', '6', None, 'St Leonards-on-Sea, England Ohio'),
 (1, 1, 'Bradley, Mr. George ("George Arthur Brayton")', 'male', None, 0, 0, '111427', 26.55, None, 'S', '9', None, 'Los Angeles, CA'),
 (1, 0, 'Brady, Mr. John Bertram', 'male', '41', 0, 0, '113054', 30.5, 'A21', 'S', None, None, 'Pomeroy, WA'),
 (1, 0, 'Brandeis, Mr. Emil', 'male', '48', 0, 0, 'PC 17591', 50.4958, 'B10', 'C', None, '208', 'Omaha, NE'),
 (1, 0, 'Brewe, Dr. Arthur Jackson', 'male', None, 0, 0, '112379', 39.6, None, 'C', None, None, 'Philadelphia, PA'),
 (1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', '44', 0, 0, 'PC 17610', 27.7208, 'B4', 'C', '6', None, 'Denver, CO'),
 (1, 1, 'Brown, Mrs. John Murray (Caroline Lane Lamson)', 'female', '59', 2, 0, '11769', 51.4792, 'C101', 'S', 'D', None, 'Belmont, MA'),
 (1, 1, 'Bucknell, Mrs. William Robert (Emma Eliza Ward)', 'female', '60', 0, 0, '11813', 76.2917, 'D15', 'C', '8', None, 'Philadelphia, PA'),
 (1, 1, 'Burns, Miss. Elizabeth Margaret', 'female', '41', 0, 0, '16966', 134.5, 'E40', 'C', '3', None, None),
 (1, 0, 'Butt, Major. Archibald Willingham', 'male', '45', 0, 0, '113050', 26.55, 'B38', 'S', None, None, 'Washington, DC'),
 (1, 0, 'Cairns, Mr. Alexander', 'male', None, 0, 0, '113798', 31.0, None, 'S', None, None, None),
 (1, 1, 'Calderhead, Mr. Edward Pennington', 'male', '42', 0, 0, 'PC 17476', 26.2875, 'E24', 'S', '5', None, 'New York, NY'),
 (1, 1, 'Candee, Mrs. Edward (Helen Churchill Hungerford)', 'female', '53', 0, 0, 'PC 17606', 27.4458, None, 'C', '6', None, 'Washington, DC'),
 (1, 1, 'Cardeza, Mr. Thomas Drake Martinez', 'male', '36', 0, 1, 'PC 17755', 512.3292, 'B51 B53 B55', 'C', '3', None, 'Austria-Hungary / Germantown, Philadelphia, PA'),
 (1, 1, 'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)', 'female', '58', 0, 1, 'PC 17755', 512.3292, 'B51 B53 B55', 'C', '3', None, 'Germantown, Philadelphia, PA'),
 (1, 0, 'Carlsson, Mr. Frans Olof', 'male', '33', 0, 0, '695', 5.0, 'B51 B53 B55', 'S', None, None, 'New York, NY'),
 (1, 0, 'Carrau, Mr. Francisco M', 'male', '28', 0, 0, '113059', 47.1, None, 'S', None, None, 'Montevideo, Uruguay'),
 (1, 0, 'Carrau, Mr. Jose Pedro', 'male', '17', 0, 0, '113059', 47.1, None, 'S', None, None, 'Montevideo, Uruguay'),
 (1, 1, 'Carter, Master. William Thornton II', 'male', '11', 1, 2, '113760', 120.0, 'B96 B98', 'S', '4', None, 'Bryn Mawr, PA'),
 (1, 1, 'Carter, Miss. Lucile Polk', 'female', '14', 1, 2, '113760', 120.0, 'B96 B98', 'S', '4', None, 'Bryn Mawr, PA'),
 (1, 1, 'Carter, Mr. William Ernest', 'male', '36', 1, 2, '113760', 120.0, 'B96 B98', 'S', 'C', None, 'Bryn Mawr, PA'),
 (1, 1, 'Carter, Mrs. William Ernest (Lucile Polk)', 'female', '36', 1, 2, '113760', 120.0, 'B96 B98', 'S', '4', None, 'Bryn Mawr, PA'),
 (1, 0, 'Case, Mr. Howard Brown', 'male', '49', 0, 0, '19924', 26.0, None, 'S', None, None, 'Ascot, Berkshire / Rochester, NY'),
 (1, 1, 'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)', 'female', None, 0, 0, '17770', 27.7208, None, 'C', '5', None, 'New York, NY'),
 (1, 0, 'Cavendish, Mr. Tyrell William', 'male', '36', 1, 0, '19877', 78.85, 'C46', 'S', None, '172', 'Little Onn Hall, Staffs'),
 (1, 1, 'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)', 'female', '76', 1, 0, '19877', 78.85, 'C46', 'S', '6', None, 'Little Onn Hall, Staffs'),
 (1, 0, 'Chaffee, Mr. Herbert Fuller', 'male', '46', 1, 0, 'W.E.P. 5734', 61.175, 'E31', 'S', None, None, 'Amenia, ND'),
 (1, 1, 'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)', 'female', '47', 1, 0, 'W.E.P. 5734', 61.175, 'E31', 'S', '4', None, 'Amenia, ND'),
 (1, 1, 'Chambers, Mr. Norman Campbell', 'male', '27', 1, 0, '113806', 53.1, 'E8', 'S', '5', None, 'New York, NY / Ithaca, NY'),
 (1, 1, 'Chambers, Mrs. Norman Campbell (Bertha Griggs)', 'female', '33', 1, 0, '113806', 53.1, 'E8', 'S', '5', None, 'New York, NY / Ithaca, NY'),
 (1, 1, 'Chaudanson, Miss. Victorine', 'female', '36', 0, 0, 'PC 17608', 262.375, 'B61', 'C', '4', None, None),
 (1, 1, 'Cherry, Miss. Gladys', 'female', '30', 0, 0, '110152', 86.5, 'B77', 'S', '8', None, 'London, England'),
 (1, 1, 'Chevre, Mr. Paul Romaine', 'male', '45', 0, 0, 'PC 17594', 29.7, 'A9', 'C', '7', None, 'Paris, France'),
 (1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', None, 0, 1, '113505', 55.0, 'E33', 'S', '6', None, 'St Leonards-on-Sea, England Ohio'),
 (1, 0, 'Chisholm, Mr. Roderick Robert Crispin', 'male', None, 0, 0, '112051', 0.0, None, 'S', None, None, 'Liverpool, England / Belfast'),
 (1, 0, 'Clark, Mr. Walter Miller', 'male', '27', 1, 0, '13508', 136.7792, 'C89', 'C', None, None, 'Los Angeles, CA'),
 (1, 1, 'Clark, Mrs. Walter Miller (Virginia McDowell)', 'female', '26', 1, 0, '13508', 136.7792, 'C89', 'C', '4', None, 'Los Angeles, CA'),
 (1, 1, 'Cleaver, Miss. Alice', 'female', '22', 0, 0, '113781', 151.55, None, 'S', '11', None, None),
 (1, 0, 'Clifford, Mr. George Quincy', 'male', None, 0, 0, '110465', 52.0, 'A14', 'S', None, None, 'Stoughton, MA'),
 (1, 0, 'Colley, Mr. Edward Pomeroy', 'male', '47', 0, 0, '5727', 25.5875, 'E58', 'S', None, None, 'Victoria, BC'),
 (1, 1, 'Compton, Miss. Sara Rebecca', 'female', '39', 1, 1, 'PC 17756', 83.1583, 'E49', 'C', '14', None, 'Lakewood, NJ'),
 (1, 0, 'Compton, Mr. Alexander Taylor Jr', 'male', '37', 1, 1, 'PC 17756', 83.1583, 'E52', 'C', None, None, 'Lakewood, NJ'),
 (1, 1, 'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)', 'female', '64', 0, 2, 'PC 17756', 83.1583, 'E45', 'C', '14', None, 'Lakewood, NJ'),
 (1, 1, 'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)', 'female', '55', 2, 0, '11770', 25.7, 'C101', 'S', '2', None, 'New York, NY'),
 (1, 0, 'Crafton, Mr. John Bertram', 'male', None, 0, 0, '113791', 26.55, None, 'S', None, None, 'Roachdale, IN'),
 (1, 0, 'Crosby, Capt. Edward Gifford', 'male', '70', 1, 1, 'WE/P 5735', 71.0, 'B22', 'S', None, '269', 'Milwaukee, WI'),
 (1, 1, 'Crosby, Miss. Harriet R', 'female', '36', 0, 2, 'WE/P 5735', 71.0, 'B22', 'S', '7', None, 'Milwaukee, WI'),
 (1, 1, 'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)', 'female', '64', 1, 1, '112901', 26.55, 'B26', 'S', '7', None, 'Milwaukee, WI'),
 (1, 0, 'Cumings, Mr. John Bradley', 'male', '39', 1, 0, 'PC 17599', 71.2833, 'C85', 'C', None, None, 'New York, NY'),
 (1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', '38', 1, 0, 'PC 17599', 71.2833, 'C85', 'C', '4', None, 'New York, NY'),
 (1, 1, 'Daly, Mr. Peter Denis', 'male', '51', 0, 0, '113055', 26.55, 'E17', 'S', '5 9', None, 'Lima, Peru'),
 (1, 1, 'Daniel, Mr. Robert Williams', 'male', '27', 0, 0, '113804', 30.5, None, 'S', '3', None, 'Philadelphia, PA'),
 (1, 1, 'Daniels, Miss. Sarah', 'female', '33', 0, 0, '113781', 151.55, None, 'S', '8', None, None),
 (1, 0, 'Davidson, Mr. Thornton', 'male', '31', 1, 0, 'F.C. 12750', 52.0, 'B71', 'S', None, None, 'Montreal, PQ'),
 (1, 1, 'Davidson, Mrs. Thornton (Orian Hays)', 'female', '27', 1, 2, 'F.C. 12750', 52.0, 'B71', 'S', '3', None, 'Montreal, PQ'),
 (1, 1, 'Dick, Mr. Albert Adrian', 'male', '31', 1, 0, '17474', 57.0, 'B20', 'S', '3', None, 'Calgary, AB'),
 (1, 1, 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'female', '17', 1, 0, '17474', 57.0, 'B20', 'S', '3', None, 'Calgary, AB'),
 (1, 1, 'Dodge, Dr. Washington', 'male', '53', 1, 1, '33638', 81.8583, 'A34', 'S', '13', None, 'San Francisco, CA'),
 (1, 1, 'Dodge, Master. Washington', 'male', '4', 0, 2, '33638', 81.8583, 'A34', 'S', '5', None, 'San Francisco, CA'),
 (1, 1, 'Dodge, Mrs. Washington (Ruth Vidaver)', 'female', '54', 1, 1, '33638', 81.8583, 'A34', 'S', '5', None, 'San Francisco, CA'),
 (1, 0, 'Douglas, Mr. Walter Donald', 'male', '50', 1, 0, 'PC 17761', 106.425, 'C86', 'C', None, '62', 'Deephaven, MN / Cedar Rapids, IA'),
 (1, 1, 'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)', 'female', '27', 1, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', '6', None, 'Montreal, PQ'),
 (1, 1, 'Douglas, Mrs. Walter Donald (Mahala Dutton)', 'female', '48', 1, 0, 'PC 17761', 106.425, 'C86', 'C', '2', None, 'Deephaven, MN / Cedar Rapids, IA'),
 (1, 1, 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")', 'female', '48', 1, 0, '11755', 39.6, 'A16', 'C', '1', None, 'London / Paris'),
 (1, 1, 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'male', '49', 1, 0, 'PC 17485', 56.9292, 'A20', 'C', '1', None, 'London / Paris'),
 (1, 0, 'Dulles, Mr. William Crothers', 'male', '39', 0, 0, 'PC 17580', 29.7, 'A18', 'C', None, '133', 'Philadelphia, PA'),
 (1, 1, 'Earnshaw, Mrs. Boulton (Olive Potter)', 'female', '23', 0, 1, '11767', 83.1583, 'C54', 'C', '7', None, 'Mt Airy, Philadelphia, PA'),
 (1, 1, 'Endres, Miss. Caroline Louise', 'female', '38', 0, 0, 'PC 17757', 227.525, 'C45', 'C', '4', None, 'New York, NY'),
 (1, 1, 'Eustis, Miss. Elizabeth Mussey', 'female', '54', 1, 0, '36947', 78.2667, 'D20', 'C', '4', None, 'Brookline, MA'),
 (1, 0, 'Evans, Miss. Edith Corse', 'female', '36', 0, 0, 'PC 17531', 31.6792, 'A29', 'C', None, None, 'New York, NY'),
 (1, 0, 'Farthing, Mr. John', 'male', None, 0, 0, 'PC 17483', 221.7792, 'C95', 'S', None, None, None),
 (1, 1, 'Flegenheim, Mrs. Alfred (Antoinette)', 'female', None, 0, 0, 'PC 17598', 31.6833, None, 'S', '7', None, 'New York, NY'),
 (1, 1, 'Fleming, Miss. Margaret', 'female', None, 0, 0, '17421', 110.8833, None, 'C', '4', None, None),
 (1, 1, 'Flynn, Mr. John Irwin ("Irving")', 'male', '36', 0, 0, 'PC 17474', 26.3875, 'E25', 'S', '5', None, 'Brooklyn, NY'),
 (1, 0, 'Foreman, Mr. Benjamin Laventall', 'male', '30', 0, 0, '113051', 27.75, 'C111', 'C', None, None, 'New York, NY'),
 (1, 1, 'Fortune, Miss. Alice Elizabeth', 'female', '24', 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', '10', None, 'Winnipeg, MB'),
 (1, 1, 'Fortune, Miss. Ethel Flora', 'female', '28', 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', '10', None, 'Winnipeg, MB'),
 (1, 1, 'Fortune, Miss. Mabel Helen', 'female', '23', 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', '10', None, 'Winnipeg, MB'),
 (1, 0, 'Fortune, Mr. Charles Alexander', 'male', '19', 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', None, None, 'Winnipeg, MB'),
 (1, 0, 'Fortune, Mr. Mark', 'male', '64', 1, 4, '19950', 263.0, 'C23 C25 C27', 'S', None, None, 'Winnipeg, MB'),
 (1, 1, 'Fortune, Mrs. Mark (Mary McDougald)', 'female', '60', 1, 4, '19950', 263.0, 'C23 C25 C27', 'S', '10', None, 'Winnipeg, MB'),
 (1, 1, 'Francatelli, Miss. Laura Mabel', 'female', '30', 0, 0, 'PC 17485', 56.9292, 'E36', 'C', '1', None, None),
 (1, 0, 'Franklin, Mr. Thomas Parham', 'male', None, 0, 0, '113778', 26.55, 'D34', 'S', None, None, 'Westcliff-on-Sea, Essex'),
 (1, 1, 'Frauenthal, Dr. Henry William', 'male', '50', 2, 0, 'PC 17611', 133.65, None, 'S', '5', None, 'New York, NY'),
 (1, 1, 'Frauenthal, Mr. Isaac Gerald', 'male', '43', 1, 0, '17765', 27.7208, 'D40', 'C', '5', None, 'New York, NY'),
 (1, 1, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 'female', None, 1, 0, 'PC 17611', 133.65, None, 'S', '5', None, 'New York, NY'),
 (1, 1, 'Frolicher, Miss. Hedwig Margaritha', 'female', '22', 0, 2, '13568', 49.5, 'B39', 'C', '5', None, 'Zurich, Switzerland'),
 (1, 1, 'Frolicher-Stehli, Mr. Maxmillian', 'male', '60', 1, 1, '13567', 79.2, 'B41', 'C', '5', None, 'Zurich, Switzerland'),
 (1, 1, 'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)', 'female', '48', 1, 1, '13567', 79.2, 'B41', 'C', '5', None, 'Zurich, Switzerland'),
 (1, 0, 'Fry, Mr. Richard', 'male', None, 0, 0, '112058', 0.0, 'B102', 'S', None, None, None),
 (1, 0, 'Futrelle, Mr. Jacques Heath', 'male', '37', 1, 0, '113803', 53.1, 'C123', 'S', None, None, 'Scituate, MA'),
 (1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', '35', 1, 0, '113803', 53.1, 'C123', 'S', 'D', None, 'Scituate, MA'),
 (1, 0, 'Gee, Mr. Arthur H', 'male', '47', 0, 0, '111320', 38.5, 'E63', 'S', None, '275', "St Anne's-on-Sea, Lancashire"),
 (1, 1, 'Geiger, Miss. Amalie', 'female', '35', 0, 0, '113503', 211.5, 'C130', 'C', '4', None, None),
 (1, 1, 'Gibson, Miss. Dorothy Winifred', 'female', '22', 0, 1, '112378', 59.4, None, 'C', '7', None, 'New York, NY'),
 (1, 1, 'Gibson, Mrs. Leonard (Pauline C Boeson)', 'female', '45', 0, 1, '112378', 59.4, None, 'C', '7', None, 'New York, NY'),
 (1, 0, 'Giglio, Mr. Victor', 'male', '24', 0, 0, 'PC 17593', 79.2, 'B86', 'C', None, None, None),
 (1, 1, 'Goldenberg, Mr. Samuel L', 'male', '49', 1, 0, '17453', 89.1042, 'C92', 'C', '5', None, 'Paris, France / New York, NY'),
 (1, 1, 'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)', 'female', None, 1, 0, '17453', 89.1042, 'C92', 'C', '5', None, 'Paris, France / New York, NY'),
 (1, 0, 'Goldschmidt, Mr. George B', 'male', '71', 0, 0, 'PC 17754', 34.6542, 'A5', 'C', None, None, 'New York, NY'),
 (1, 1, 'Gracie, Col. Archibald IV', 'male', '53', 0, 0, '113780', 28.5, 'C51', 'C', 'B', None, 'Washington, DC'),
 (1, 1, 'Graham, Miss. Margaret Edith', 'female', '19', 0, 0, '112053', 30.0, 'B42', 'S', '3', None, 'Greenwich, CT'),
 (1, 0, 'Graham, Mr. George Edward', 'male', '38', 0, 1, 'PC 17582', 153.4625, 'C91', 'S', None, '147', 'Winnipeg, MB'),
 (1, 1, 'Graham, Mrs. William Thompson (Edith Junkins)', 'female', '58', 0, 1, 'PC 17582', 153.4625, 'C125', 'S', '3', None, 'Greenwich, CT'),
 (1, 1, 'Greenfield, Mr. William Bertram', 'male', '23', 0, 1, 'PC 17759', 63.3583, 'D10 D12', 'C', '7', None, 'New York, NY'),
 (1, 1, 'Greenfield, Mrs. Leo David (Blanche Strouse)', 'female', '45', 0, 1, 'PC 17759', 63.3583, 'D10 D12', 'C', '7', None, 'New York, NY'),
 (1, 0, 'Guggenheim, Mr. Benjamin', 'male', '46', 0, 0, 'PC 17593', 79.2, 'B82 B84', 'C', None, None, 'New York, NY'),
 (1, 1, 'Harder, Mr. George Achilles', 'male', '25', 1, 0, '11765', 55.4417, 'E50', 'C', '5', None, 'Brooklyn, NY'),
 (1, 1, 'Harder, Mrs. George Achilles (Dorothy Annan)', 'female', '25', 1, 0, '11765', 55.4417, 'E50', 'C', '5', None, 'Brooklyn, NY'),
 (1, 1, 'Harper, Mr. Henry Sleeper', 'male', '48', 1, 0, 'PC 17572', 76.7292, 'D33', 'C', '3', None, 'New York, NY'),
 (1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', '49', 1, 0, 'PC 17572', 76.7292, 'D33', 'C', '3', None, 'New York, NY'),
 (1, 0, 'Harrington, Mr. Charles H', 'male', None, 0, 0, '113796', 42.4, None, 'S', None, None, None),
 (1, 0, 'Harris, Mr. Henry Birkhardt', 'male', '45', 1, 0, '36973', 83.475, 'C83', 'S', None, None, 'New York, NY'),
 (1, 1, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'female', '35', 1, 0, '36973', 83.475, 'C83', 'S', 'D', None, 'New York, NY'),
 (1, 0, 'Harrison, Mr. William', 'male', '40', 0, 0, '112059', 0.0, 'B94', 'S', None, '110', None),
 (1, 1, 'Hassab, Mr. Hammad', 'male', '27', 0, 0, 'PC 17572', 76.7292, 'D49', 'C', '3', None, None),
 (1, 1, 'Hawksford, Mr. Walter James', 'male', None, 0, 0, '16988', 30.0, 'D45', 'S', '3', None, 'Kingston, Surrey'),
 (1, 1, 'Hays, Miss. Margaret Bechstein', 'female', '24', 0, 0, '11767', 83.1583, 'C54', 'C', '7', None, 'New York, NY'),
 (1, 0, 'Hays, Mr. Charles Melville', 'male', '55', 1, 1, '12749', 93.5, 'B69', 'S', None, '307', 'Montreal, PQ'),
 (1, 1, 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)', 'female', '52', 1, 1, '12749', 93.5, 'B69', 'S', '3', None, 'Montreal, PQ'),
 (1, 0, 'Head, Mr. Christopher', 'male', '42', 0, 0, '113038', 42.5, 'B11', 'S', None, None, 'London / Middlesex'),
 (1, 0, 'Hilliard, Mr. Herbert Henry', 'male', None, 0, 0, '17463', 51.8625, 'E46', 'S', None, None, 'Brighton, MA'),
 (1, 0, 'Hipkins, Mr. William Edward', 'male', '55', 0, 0, '680', 50.0, 'C39', 'S', None, None, 'London / Birmingham'),

Part 1 - Employees

Q1

In [12]:
%%sql
SELECT count(*) as 'number of employees'
FROM Employee

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(8,)]

Q2

In [13]:
%%sql
SELECT count(*) as 'number of employees'
FROM EMPLOYEE
WHERE FNAME like '%J%' AND LNAME like 'S%'

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(1,)]

Q3

In [14]:
%%sql
SELECT SEX,count(*) as 'number of employees'
FROM EMPLOYEE
GROUP by SEX

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('F', 3), ('M', 5)]

Q4

In [16]:
%%sql
SELECT PNAME
FROM
(SELECT PNAME,count(*) as amount
FROM WORKS_ON JOIN PROJECT on WORKS_ON.PNO=PROJECT.PNUMBER
GROUP by PNAME
HAVING amount=
(SELECT max(amount)
FROM
(
SELECT PNAME,count(*) as amount
FROM WORKS_ON JOIN PROJECT on WORKS_ON.PNO=PROJECT.PNUMBER
GROUP by PNAME)))

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Computerization',), ('Newbenefits',), ('Producty',), ('Reorganization',)]

Q5

In [20]:
%%sql
SELECT FNAME
FROM
(SELECT EMPLOYEE.FNAME,count(*) as 'number of children'
FROM EMPLOYEE JOIN DEPENDENT on EMPLOYEE.SSN=DEPENDENT.ESSN
WHERE DEPENDENT.RELATIONSHIP='SON' or DEPENDENT.RELATIONSHIP='DAUGHTER'
GROUP by EMPLOYEE.FNAME
HAVING count(*)>2)

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[]

Q6

In [21]:
%%sql
SELECT DNUMBER,count(*) as 'number of employees'
FROM EMPLOYEE
GROUP by DNUMBER

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(1, 1), (4, 3), (5, 4)]

Q7

In [24]:
%%sql
SELECT DNAME
FROM
(SELECT EMPLOYEE.DNUMBER,DNAME,count(*) as amount
FROM EMPLOYEE JOIN DEPARTMENT on EMPLOYEE.DNUMBER=DEPARTMENT.DNUMBER
GROUP by EMPLOYEE.DNUMBER
HAVING amount=
(SELECT max(amount)
FROM
(SELECT EMPLOYEE.DNUMBER,DNAME,count(*) as amount
FROM EMPLOYEE JOIN DEPARTMENT on EMPLOYEE.DNUMBER=DEPARTMENT.DNUMBER
GROUP by EMPLOYEE.DNUMBER)))

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Research',)]

Q8

In [26]:
%%sql
SELECT PNO as 'Project number',sum(hours) as 'total hours'
FROM WORKS_ON
GROUP by PNO
ORDER by sum(HOURS)

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(20, 25), (2, 37.5), (3, 50), (1, 52.5), (10, 55), (30, 55)]

Q9

In [28]:
%%sql
SELECT DNUMBER as 'Department number',sum(salary) as 'total salary'
FROM EMPLOYEE
GROUP by DNUMBER
ORDER by sum(SALARY) DESC

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(5, 133000), (4, 93000), (1, 55000)]

Q10

In [29]:
%%sql
SELECT FNAME,LNAME
FROM EMPLOYEE
WHERE SSN in 
(SELECT SUPERSSN
FROM
((SELECT SUPERSSN,count(*) as amount
FROM EMPLOYEE
GROUP by SUPERSSN
HAVING amount = 
(SELECT max(amount)
FROM
(SELECT SUPERSSN,count(*) as amount
FROM EMPLOYEE
GROUP by SUPERSSN)))))

   sqlite:////content/Airbnb.db
 * sqlite:////content/Workers.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Franklin', 'Wong')]

Part 2 - Titanic

Q1

In [ ]:
%%sql
select count(*)
from titanic
where fare>50 and pclass=1

   sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[(209,)]

Q2

In [ ]:
%%sql
select case
when count(*)>0 then 'there is'
else 'there is not'
end as result
from titanic
where pclass=2 and fare>(select min(fare) from titanic where pclass=1)

   sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[('there is',)]

Q3

In [ ]:
%%sql
select case
when count(*)>0 then 'there is Jack on board'
else 'there is no Jack on board'
end as existence
from titanic
where name like '%Jack %'

   sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[('there is no Jack on board',)]

Q4

In [ ]:
%%sql 
select sex,pclass,total_survived/passengers*100 as 'chances of survival'
from 
(select sex,pclass,cast(sum(survived) as float) as total_survived,cast(count(*) as float) as passengers
from titanic
group by sex,pclass
having sex<>'')

   sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
 * sqlite:////content/titanic.db
Done.

[('female', 1, 96.52777777777779),
 ('female', 2, 88.67924528301887),
 ('female', 3, 49.074074074074076),
 ('male', 1, 34.07821229050279),
 ('male', 2, 14.619883040935672),
 ('male', 3, 15.212981744421908)]

Part 3 - Pokemon

Q1

In [ ]:
%%sql
SELECT Pokemon.trainerID,trainername
FROM pokemon JOIN trainers on Pokemon.trainerID = Trainers.trainerID
GROUP BY Pokemon.trainerID
HAVING Pokemon.pokelevel = (SELECT MAX(pokelevel) FROM pokemon)

   sqlite:////content/Airbnb.db
 * sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(1258, 'Cool♀'),
 (1259, 'Cool♀'),
 (1260, 'Cool♂'),
 (1261, 'Cool♂'),
 (1262, 'Cool♀'),
 (1263, 'Cool♀'),
 (1264, 'Cool♂'),
 (1265, 'Cool♂'),
 (1266, 'Cool♀'),
 (1267, 'Cool♀'),
 (1268, 'Cool♂'),
 (1269, 'Cool♂'),
 (1270, 'Cool♀'),
 (1271, 'Cool♀'),
 (1272, 'Cool♂'),
 (1273, 'Cool♂'),
 (1280, 'Cooltrainer♀ Floria'),
 (1281, 'Cooltrainer♀ Floria'),
 (1284, 'Cooltrainer♂ Marty'),
 (1285, 'Cooltrainer♂ Marty'),
 (1312, 'Cooltrainer♂ Forgon'),
 (1317, 'Cooltrainer♀ Moden'),
 (1320, 'Cooltrainer♀ Rask'),
 (1325, 'Cooltrianer♂ Vanhub'),
 (1335, 'Cooltrainer♀ Dodin'),
 (1351, 'Cooltrainer♀ Rapeel'),
 (1567, 'Athlete♂ Naga'),
 (1728, 'Bandana Guy Kaler'),
 (2250, 'Birdboy'),
 (2251, 'Birdboy'),
 (2252, 'Birdboy'),
 (2253, 'Birdboy'),
 (2254, 'Birdboy'),
 (2255, 'Birdboy'),
 (2256, 'Birdboy'),
 (2257, 'Birdboy'),
 (2258, 'Bird Keeper Adam'),
 (2259, 'Bird Keeper Adam'),
 (2458, 'Judoboy'),
 (2459, 'Judoboy'),
 (2460, 'Judoboy'),
 (2461, 'Judoboy'),
 (2462, 'Judoboy'),
 (2463, 'Judoboy'),
 (2464, 'Judoboy'),
 (2465, 'Judoboy'),
 (2470, 'Blackbelt Yang'),
 (2471, 'Blackbelt Yang'),
 (2542, 'Bodybuilder♀ Elkain'),
 (2550, 'Bodybuilder♀ Powit'),
 (3043, 'Chaser♂ Chotle'),
 (3045, 'Chaser♀ Ethior'),
 (3080, 'Chaser♀ Quelis'),
 (3420, 'Crush Girl Rebecca'),
 (3421, 'Crush Girl Rebecca'),
 (4084, 'Cool♀'),
 (4085, 'Cool♀'),
 (4086, 'Cool♂'),
 (4087, 'Cool♂'),
 (4088, 'Cool♀'),
 (4089, 'Cool♀'),
 (4090, 'Cool♂'),
 (4091, 'Cool♂'),
 (4092, 'Cool♀'),
 (4093, 'Cool♀'),
 (4094, 'Cool♂'),
 (4095, 'Cool♂'),
 (4096, 'Cool♀'),
 (4097, 'Cool♀'),
 (4098, 'Cool♂'),
 (4099, 'Cool♂'),
 (4106, 'Cooltrainer♀ Floria'),
 (4107, 'Cooltrainer♀ Floria'),
 (4110, 'Cooltrainer♂ Marty'),
 (4111, 'Cooltrainer♂ Marty'),
 (4138, 'Cooltrainer♂ Forgon'),
 (4143, 'Cooltrainer♀ Moden'),
 (4146, 'Cooltrainer♀ Rask'),
 (4151, 'Cooltrianer♂ Vanhub'),
 (4161, 'Cooltrainer♀ Dodin'),
 (4177, 'Cooltrainer♀ Rapeel'),
 (4393, 'Athlete♂ Naga'),
 (4554, 'Bandana Guy Kaler'),
 (5076, 'Birdboy'),
 (5077, 'Birdboy'),
 (5078, 'Birdboy'),
 (5079, 'Birdboy'),
 (5080, 'Birdboy'),
 (5081, 'Birdboy'),
 (5082, 'Birdboy'),
 (5083, 'Birdboy'),
 (5084, 'Bird Keeper Adam'),
 (5085, 'Bird Keeper Adam'),
 (5284, 'Judoboy'),
 (5285, 'Judoboy'),
 (5286, 'Judoboy'),
 (5287, 'Judoboy'),
 (5288, 'Judoboy'),
 (5289, 'Judoboy'),
 (5290, 'Judoboy'),
 (5291, 'Judoboy'),
 (5296, 'Blackbelt Yang'),
 (5297, 'Blackbelt Yang'),
 (5368, 'Bodybuilder♀ Elkain'),
 (5376, 'Bodybuilder♀ Powit'),
 (5869, 'Chaser♂ Chotle'),
 (5871, 'Chaser♀ Ethior'),
 (5906, 'Chaser♀ Quelis'),
 (6246, 'Crush Girl Rebecca'),
 (6247, 'Crush Girl Rebecca'),
 (6805, 'Fisherman Chase'),
 (6806, 'Fisherman Chase'),
 (7365, 'Hunter♀ Bigon'),
 (7374, 'Hunter♂ Kolot'),
 (7565, 'Lady Charlotte'),
 (7706, 'Lass Mikaela'),
 (7827, 'Lass Terry'),
 (7828, 'Lass Terry'),
 (8043, 'Myth Trainer Infin'),
 (8044, 'Myth Trainer Inity'),
 (8053, 'Navigator Kerdin'),
 (8280, 'Gambler'),
 (8281, 'Gambler'),
 (8282, 'Gambler'),
 (8283, 'Gambler'),
 (8284, 'Gambler'),
 (8285, 'Gambler'),
 (8286, 'Gambler'),
 (8287, 'Gambler'),
 (8391, 'Picnicker Camryn'),
 (8751, 'Pokémon Ranger♀ Chelsea'),
 (8752, 'Pokémon Ranger♀ Chelsea'),
 (8762, 'Pokémon Ranger♂ Trenton'),
 (8763, 'Pokémon Ranger♂ Trenton'),
 (9253, 'Rich Boy Guyit'),
 (9261, 'Rich Boy Venak'),
 (9320, 'Rider♀ Marley'),
 (9323, 'Rider♀ Porta'),
 (9324, 'Rider♀ Pulink'),
 (9343, 'Rider♂ Lorgo'),
 (9449, 'Cue Ball Gabriel'),
 (9472, 'Cueball'),
 (9473, 'Cueball'),
 (9474, 'Cueball'),
 (9475, 'Cueball'),
 (9476, 'Cueball'),
 (9477, 'Cueball'),
 (9478, 'Cueball'),
 (9479, 'Cueball'),
 (9558, 'Sailor Alberto'),
 (9559, 'Sailor Brenan'),
 (9625, 'Sailor Morkor'),
 (9820, 'Scientist Zachary'),
 (9888, 'Lab Man'),
 (9889, 'Lab Man'),
 (9890, 'Lab Man'),
 (9891, 'Lab Man'),
 (9892, 'Lab Man'),
 (9893, 'Lab Man'),
 (9894, 'Lab Man'),
 (9895, 'Lab Man'),
 (9898, 'Scientist Craig'),
 (9899, 'Scientist Craig'),
 (9932, 'Researcher Krilok'),
 (10077, 'Sim Trainer Geplin'),
 (10114, 'Sis and Bro Axe & Ren'),
 (10115, 'Sis and Bro Kat & Kitt'),
 (10165, 'Skier Kathy'),
 (10166, 'Skier Kathy'),
 (10321, 'Super Nerd Owen'),
 (10343, 'Supertrainer♂ Buril'),
 (10345, 'Supertrainer♂ Codel'),
 (10347, 'Supertrainer♀ Garvon'),
 (10348, 'Supertrainer♀ Grang'),
 (10349, 'Supertrainer♂ Gravet'),
 (10351, 'Supertrainer♂ Hufnak'),
 (10352, 'Supertrainer♀ Huron'),
 (10354, 'Supertrainer♂ Lagin'),
 (10355, 'Supertrainer♂ Okamoo'),
 (10356, 'Supertrainer♀ Saya'),
 (10357, 'Supertrainer♂ Shoo'),
 (10358, 'Supertrainer♂ Shun'),
 (10535, 'Swimmer♂ Braden'),
 (10567, 'Swimmer♀ Shania'),
 (10854, 'Teacher Kaede'),
 (10856, 'Teacher Lagron'),
 (11248, 'Tuber Priscilla'),
 (11317, 'Twins Jen & Kira'),
 (11557, 'Worker Bomber'),
 (11569, 'Worker Kaster'),
 (11602, 'Young Couple Alek & Emy'),
 (11696, 'Youngster Cole')]

Q2

In [ ]:
%%sql
SELECT pokename
FROM Pokemon JOIN Trainers on Pokemon.trainerID=Trainers.trainerID
WHERE pokename like '%P%' AND trainername like '%A%'

   sqlite:////content/Airbnb.db
 * sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Vileplume',),
 ('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Vileplume',),
 ('Weepinbell',),
 ('Persian',),
 ('Parasect',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Rapidash',),
 ('Rapidash',),
 ('Rapidash',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Pikachu',),
 ('Skiploom',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Trapinch',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Trapinch',),
 ('Pelipper',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Spinda',),
 ('Spinda',),
 ('Spinda',),
 ('Exploud',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Tropius',),
 ('Spinda',),
 ('Dusclops',),
 ('Nosepass',),
 ('Sharpedo',),
 ('Pelipper',),
 ('Jigglypuff',),
 ('Persian',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Paras',),
 ('Parasect',),
 ('Poliwhirl',),
 ('Lapras',),
 ('Machamp',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Persian',),
 ('Rapidash',),
 ('Persian',),
 ('Rapidash',),
 ('Persian',),
 ('Ponyta',),
 ('Rapidash',),
 ('Vulpix',),
 ('Ponyta',),
 ('Ambipom',),
 ('Rapidash',),
 ('Ambipom',),
 ('Rapidash',),
 ('Ambipom',),
 ('Pachirisu',),
 ('Pelipper',),
 ('Skorupi',),
 ('Lopunny',),
 ('Pelipper',),
 ('Hippopotas',),
 ('Pelipper',),
 ('Hippopotas',),
 ('Pelipper',),
 ('Tropius',),
 ('Ampharos',),
 ('Tropius',),
 ('Dusclops',),
 ('Drapion',),
 ('Ponyta',),
 ('Primeape',),
 ('Lopunny',),
 ('Ponyta',),
 ('Purugly',),
 ('Rapidash',),
 ('Persian',),
 ('Hypno',),
 ('Dunsparce',),
 ('Rapidash',),
 ('Rampardos',),
 ('Pinsir',),
 ('Poliwhirl',),
 ('Pelipper',),
 ('Lopunny',),
 ('Lopunny',),
 ('Rampardos',),
 ('Aipom',),
 ('Ambipom',),
 ('Porygon2',),
 ('Lopunny',),
 ('Tropius',),
 ('Ampharos',),
 ('Tropius',),
 ('Probopass',),
 ('Dusclops',),
 ('Dusclops',),
 ('Piloswine',),
 ('Staraptor',),
 ('Staraptor',),
 ('Drapion',),
 ('Staraptor',),
 ('Hippopotas',),
 ('Jumpluff',),
 ('Ampharos',),
 ('Primeape',),
 ('Tropius',),
 ('Rapidash',),
 ('Seviper',),
 ('Persian',),
 ('Lopunny',),
 ('Rampardos',),
 ('Pinsir',),
 ('Lopunny',),
 ('Lopunny',),
 ('Rampardos',),
 ('Pelipper',),
 ('Pupitar',),
 ('Spinda',),
 ('Mareep',),
 ('Mareep',),
 ('Poliwhirl',),
 ('Vaporeon',),
 ('Parasect',),
 ('Vaporeon',),
 ('Rapidash',),
 ('Rapidash',),
 ('Ampharos',),
 ('Rapidash',),
 ('Ampharos',),
 ('Rapidash',),
 ('Ampharos',),
 ('Pikachu',),
 ('Mareep',),
 ('Pidgeot',),
 ('Grumpig',),
 ('Simipour',),
 ('Tropius',),
 ('Scolipede',),
 ('Simipour',),
 ('Pawniard',),
 ('Liepard',),
 ('Purugly',),
 ('Espeon',),
 ('Lapras',),
 ('Pawniard',),
 ('Simipour',),
 ('Vaporeon',),
 ('Palpitoad',),
 ('Lopunny',),
 ('Lampent',),
 ('Sigilyph',),
 ('Tropius',),
 ('Grumpig',),
 ('Pelipper',),
 ('Vaporeon',),
 ('Scolipede',),
 ('Ampharos',),
 ('Camerupt',),
 ('Espeon',),
 ('Drapion',),
 ('Pelipper',),
 ('Pinsir',),
 ('Sharpedo',),
 ('Helioptile',),
 ('Ampharos',),
 ('Piloswine',),
 ('Sigilyph',),
 ('Rhyperior',),
 ('Pelipper',),
 ('Pelipper',),
 ('Camerupt',),
 ('Pelipper',),
 ('Camerupt',),
 ('Purugly',),
 ('Pelipper',),
 ('Camerupt',),
 ('Lapras',),
 ('Dusclops',),
 ('Seviper',),
 ('Tropius',),
 ('Pinsir',),
 ('Tropius',),
 ('Lapras',),
 ('Vulpix',),
 ('Sharpedo',),
 ('Slowpoke',),
 ('Machamp',),
 ('Primeape',),
 ('Pinsir',),
 ('Hypno',),
 ('Poliwrath',),
 ('Hypno',),
 ('Rapidash',),
 ('Politoed',),
 ('Espeon',),
 ('Jigglypuff',),
 ('Skiploom',),
 ('Persian',),
 ('Machamp',),
 ('Lapras',),
 ('Hoppip',),
 ('Togepi',),
 ('Vulpix',),
 ('Sceptile',),
 ('Swampert',),
 ('Mudkip',),
 ('Typhlosion',),
 ('Ampharos',),
 ('Espeon',),
 ('Donphan',),
 ('Swampert',),
 ('Jumpluff',),
 ('Tropius',),
 ('Ampharos',),
 ('Dusclops',),
 ('Donphan',),
 ('Clamperl',),
 ('Espeon',),
 ('Pineco',),
 ('Skiploom',),
 ('Jigglypuff',),
 ('Trapinch',),
 ('Sceptile',),
 ('Plusle',),
 ('Pupitar',),
 ('Pelipper',),
 ('Spoink',),
 ('Grumpig',),
 ('Togepi',),
 ('Jigglypuff',),
 ('Togepi',),
 ('Clamperl',),
 ('Zapdos',),
 ('Spoink',),
 ('Spinda',),
 ('Grumpig',),
 ('Spinda',),
 ('Machamp',),
 ('Lileep',),
 ('Dusclops',),
 ('Lapras',),
 ('Swampert',),
 ('Spoink',),
 ('Jumpluff',),
 ('Hypno',),
 ('Parasect',),
 ('Primeape',),
 ('Porygon2',),
 ('Pelipper',),
 ('Poochyena',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Sharpedo',),
 ('Pineco',),
 ('Dusclops',),
 ('Tropius',),
 ('Vileplume',),
 ('Corphish',),
 ('Phanpy',),
 ('Nosepass',),
 ('Lileep',),
 ('Jigglypuff',),
 ('Pelipper',),
 ('Jumpluff',),
 ('Sharpedo',),
 ('Hitmontop',),
 ('Trapinch',),
 ('Marshtomp',),
 ('Piloswine',),
 ('Pinsir',),
 ('Dusclops',),
 ('Marshtomp',),
 ('Vileplume',),
 ('Dusclops',),
 ('Porygon2',),
 ('Ampharos',),
 ('Phanpy',),
 ('Hitmontop',),
 ('Marshtomp',),
 ('Mudkip',),
 ('Exploud',),
 ('Machamp',),
 ('Typhlosion',),
 ('Espeon',),
 ('Spinda',),
 ('Machop',),
 ('Vileplume',),
 ('Bellsprout',),
 ('Weepinbell',),
 ('Vileplume',),
 ('Sigilyph',),
 ('Camerupt',),
 ('Sigilyph',),
 ('Psyduck',),
 ('Pineco',),
 ('Pikachu',),
 ('Vulpix',),
 ('Pikachu',),
 ('Vulpix',),
 ('Jumpluff',),
 ('Wooper',),
 ('Jumpluff',),
 ('Camerupt',),
 ('Wooper',),
 ('Trapinch',),
 ('Sceptile',),
 ('Camerupt',),
 ('Corphish',),
 ('Corphish',),
 ('Phanpy',),
 ('Wooper',),
 ('Tropius',),
 ('Sharpedo',),
 ('Dusclops',),
 ('Marshtomp',),
 ('Jigglypuff',),
 ('Spheal',),
 ('Pupitar',),
 ('Shuppet',),
 ('Wooper',),
 ('Sharpedo',),
 ('Dusclops',),
 ('Porygon2',),
 ('Hoppip',),
 ('Pikachu',),
 ('Psyduck',),
 ('Mudkip',),
 ('Pinsir',),
 ('Bisharp',),
 ('Pansear',),
 ('Panpour',),
 ('Simipour',),
 ('Simipour',),
 ('Liepard',),
 ('Liepard',),
 ('Scolipede',),
 ('Scolipede',),
 ('Scolipede',),
 ('Scolipede',),
 ('Bisharp',),
 ('Pansear',),
 ('Panpour',),
 ('Simipour',),
 ('Simipour',),
 ('Liepard',),
 ('Liepard',),
 ('Scolipede',),
 ('Scolipede',),
 ('Scolipede',),
 ('Scolipede',),
 ('Pachirisu',),
 ('Staraptor',),
 ('Porygon-Z',),
 ('Pidove',),
 ('Petilil',),
 ('Palpitoad',),
 ('Liepard',),
 ('Sigilyph',),
 ('Poochyena',),
 ('Archeops',),
 ('Spheal',),
 ('Pidove',),
 ('Skorupi',),
 ('Pinsir',),
 ('Lileep',),
 ('Pansear',),
 ('Panpour',),
 ('Pansage',),
 ('Psyduck',),
 ('Psyduck',),
 ('Psyduck',),
 ('Pupitar',),
 ('Wooper',),
 ('Wooper',),
 ('Vulpix',),
 ('Grumpig',),
 ('Pupitar',),
 ('Clamperl',),
 ('Piloswine',),
 ('Machamp',),
 ('Spinda',),
 ('Grumpig',),
 ('Togepi',),
 ('Dunsparce',),
 ('Exploud',),
 ('Tropius',),
 ('Seviper',),
 ('Sceptile',),
 ('Psyduck',),
 ('Hoppip',),
 ('Spoink',),
 ('Piloswine',),
 ('Zapdos',),
 ('Primeape',),
 ('Persian',),
 ('Pachirisu',),
 ('Purugly',),
 ('Grumpig',),
 ('Piloswine',),
 ('Zapdos',),
 ('Primeape',),
 ('Persian',),
 ('Pachirisu',),
 ('Purugly',),
 ('Grumpig',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Hitmontop',),
 ('Machop',),
 ('Poliwrath',),
 ('Poliwrath',),
 ('Primeape',),
 ('Machop',),
 ('Bellsprout',),
 ('Bellsprout',),
 ('Bellsprout',),
 ('Bellsprout',),
 ('Pikachu',),
 ('Vulpix',),
 ('Pidgeotto',),
 ('Poliwag',),
 ('Poliwag',),
 ('Poliwag',),
 ('Vileplume',),
 ('Paras',),
 ('Parasect',),
 ('Hoppip',),
 ('Skiploom',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Sharpedo',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Clamperl',),
 ('Corphish',),
 ('Sharpedo',),
 ('Bellsprout',),
 ('Bellsprout',),
 ('Pidgeotto',),
 ('Pidgeot',),
 ('Pikachu',),
 ('Persian',),
 ('Bellsprout',),
 ('Bellsprout',),
 ('Purugly',),
 ('Psyduck',),
 ('Lopunny',),
 ('Psyduck',),
 ('Lopunny',),
 ('Vileplume',),
 ('Paras',),
 ('Parasect',),
 ('Hoppip',),
 ('Skiploom',),
 ('Espurr',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Seviper',),
 ('Pidgeot',),
 ('Kabutops',),
 ('Kabutops',),
 ('Vaporeon',),
 ('Pidgeotto',),
 ('Pidgeot',),
 ('Skiploom',),
 ('Pidgeotto',),
 ('Jumpluff',),
 ('Persian',),
 ('Vileplume',),
 ('Jumpluff',),
 ('Politoed',),
 ('Aipom',),
 ('Mareep',),
 ('Ponyta',),
 ('Pikachu',),
 ('Pidgey',),
 ('Pineco',),
 ('Wurmple',),
 ('Sharpedo',),
 ('Poliwhirl',),
 ('Ponyta',),
 ('Ponyta',),
 ('Rapidash',),
 ('Ponyta',),
 ('Ponyta',),
 ('Hypno',),
 ('Hypno',),
 ('Hypno',),
 ('Gulpin',),
 ('Gulpin',),
 ('Skorupi',),
 ('Spearow',),
 ('Pidgey',),
 ('Pidgeotto',),
 ('Pidgey',),
 ('Pidgeot',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Pidgeot',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Pelipper',),
 ('Tropius',),
 ('Pelipper',),
 ('Tropius',),
 ('Pidgey',),
 ('Pidgeotto',),
 ('Spearow',),
 ('Spearow',),
 ('Spearow',),
 ('Spearow',),
 ('Spearow',),
 ('Spearow',),
 ('Spearow',),
 ('Pidgey',),
 ('Pidgeotto',),
 ('Staraptor',),
 ('Pidgeot',),
 ('Pidgeot',),
 ('Spearow',),
 ('Pidgey',),
 ('Pidgeotto',),
 ('Spearow',),
 ('Pidgey',),
 ('Pidgeot',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Pidgeot',),
 ('Pidgeot',),
 ('Pidgeot',),
 ('Pelipper',),
 ('Zapdos',),
 ('Pidgey',),
 ('Spearow',),
 ('Pidgeotto',),
 ('Pidgeotto',),
 ('Machop',),
 ('Primeape',),
 ('Machop',),
 ('Primeape',),
 ('Primeape',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Primeape',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machamp',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Primeape',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Primeape',),
 ('Machop',),
 ('Machamp',),
 ('Primeape',),
 ('Poliwrath',),
 ('Poliwrath',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Primeape',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Hitmontop',),
 ('Machamp',),
 ('Infernape',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machamp',),
 ('Machamp',),
 ('Primeape',),
 ('Machamp',),
 ('Machamp',),
 ('Primeape',),
 ('Poliwrath',),
 ('Machop',),
 ('Primeape',),
 ('Poliwrath',),
 ('Machamp',),
 ('Machamp',),
 ('Hitmontop',),
 ('Pinsir',),
 ('Hitmontop',),
 ('Pangoro',),
 ('Machop',),
 ('Machamp',),
 ('Pangoro',),
 ('Rampardos',),
 ('Machop',),
 ('Machamp',),
 ('Machop',),
 ('Machop',),
 ('Machop',),
 ('Machamp',),
 ('Primeape',),
 ('Machamp',),
 ('Machop',),
 ('Primeape',),
 ('Poliwrath',),
 ('Machamp',),
 ('Pangoro',),
 ('Machamp',),
 ('Hitmontop',),
 ('Pinsir',),
 ('Primeape',),
 ('Hitmontop',),
 ('Primeape',),
 ('Poliwrath',),
 ('Lapras',),
 ('Vaporeon',),
 ('Vaporeon',),
 ('Zapdos',),
 ('Spinda',),
 ('Pupitar',),
 ('Pikachu',),
 ('Porygon2',),
 ('Porygon2',),
 ('Exploud',),
 ('Dunsparce',),
 ('Piloswine',),
 ('Dunsparce',),
 ('Piloswine',),
 ('Dunsparce',),
 ('Typhlosion',),
 ('Pelipper',),
 ('Machop',),
 ('Dusclops',),
 ('Vileplume',),
 ('Ampharos',),
 ('Porygon2',),
 ('Donphan',),
 ('Piloswine',),
 ('Spinda',),
 ('Grumpig',),
 ('Pikachu',),
 ('Mudkip',),
 ('Psyduck',),
 ('Machop',),
 ('Phanpy',),
 ('Hitmontop',),
 ('Donphan',),
 ('Wurmple',),
 ('Togepi',),
 ('Machamp',),
 ('Pawniard',),
 ('Scolipede',),
 ('Garchomp',),
 ('Scolipede',),
 ('Seviper',),
 ('Kabutops',),
 ('Rampardos',),
 ('Porygon-Z',),
 ('Infernape',),
 ('Archeops',),
 ('Zapdos',),
 ('Grumpig',),
 ('Primeape',),
 ('Machamp',),
 ('Machamp',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Metapod',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Paras',),
 ('Pinsir',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ('Metapod',),
 ('Metapod',),
 ('Metapod',),
 ('Paras',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Pinsir',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Wurmple',),
 ('Caterpie',),
 ('Caterpie',),
 ('Caterpie',),
 ...]

Q3

In [ ]:
%%sql
SELECT trainername
FROM Trainers JOIN
(SELECT Pokemon.trainerID, count(*) as poke_count
FROM Pokemon JOIN Trainers on Pokemon.trainerID = Trainers.trainerID
GROUP by Trainers.trainerID
HAVING poke_count =
(SELECT max(poke_count)
FROM
(
SELECT Pokemon.trainerID, count(*) as poke_count
from Pokemon JOIN Trainers on Pokemon.trainerID = Trainers.trainerID
GROUP by Trainers.trainerID
))) as new_table on Trainers.trainerID = new_table.trainerID

   sqlite:////content/Airbnb.db
 * sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cooltrainer♀ Becky',),
 ('Cooltrainer♂ Conner',),
 ('Cooltrainer♀ Floria',),
 ('Cooltrainer♀ Gloria',),
 ('Cooltrainer♀ Gloria',),
 ('Cooltrainer♂ Marty',),
 ('Cooltrainer♂ Marty',),
 ('Cooltrainer♂ Vince',),
 ('Cooltrainer♂ Vince',),
 ('Cooltrainer♀ Atilo',),
 ('Cooltrainer♂ Berki',),
 ('Cooltrainer♂ Cruik',),
 ('Cooltrainer♂ Dazon',),
 ('Cooltrainer♂ Desid',),
 ('Cooltrainer♀ Detta',),
 ('Cooltrainer♂ Dillot',),
 ('Cooltrainer♂ Farfin',),
 ('Cooltrainer♂ Forgon',),
 ('Cooltrainer♀ Gilly',),
 ('Cooltrainer♀ Gosney',),
 ('Cooltrainer♂ Hebel',),
 ('Cooltrainer♀ Levens',),
 ('Cooltrainer♀ Moden',),
 ('Cooltrainer♂ Morfon',),
 ('Cooltrainer♂ Moril',),
 ('Cooltrainer♀ Rask',),
 ('Cooltrainer♀ Rateis',),
 ('Cooltrainer♀ Rosno',),
 ('Cooltrianer♂ Shadd',),
 ('Cooltrainer♀ Tynan',),
 ('Cooltrianer♂ Vanhub',),
 ('Cooltrainer♀ Veron',),
 ('Cooltrainer♀ Zoel',),
 ('Cooltrainer♀ Ebson',),
 ('Cooltrainer♂ Klept',),
 ('Area Leader Axley',),
 ('Area Leader Cryal',),
 ('Area Leader Dessa',),
 ('Area Leader Erben',),
 ('Area Leader Glydin',),
 ('Area Leader Leven',),
 ('Area Leader Slewis',),
 ('Area Leader Vannos',),
 ('Area Leader Vario',),
 ('Area Leader Altor',),
 ('Area Leader Atrice',),
 ('Area Leader Elion',),
 ('Area Leader Konaik',),
 ('Area Leader Kucher',),
 ('Area Leader Langot',),
 ('Area Leader Mortac',),
 ('Area Leader Neblek',),
 ('Area Leader Vernice',),
 ('Athlete♀ Aleja',),
 ('Athlete♂ Busik',),
 ('Athlete♂ Deron',),
 ('Athlete♀ Dilasi',),
 ('Athlete♂ Gatik',),
 ('Athlete♂ Gulor',),
 ('Athlete♀ Kimber',),
 ('Athlete♂ Latrin',),
 ('Athlete♀ Mazzel',),
 ('Athlete♂ Menzon',),
 ('Athlete♂ Naga',),
 ('Athlete♀ Nomol',),
 ('Athlete♀ Pasha',),
 ('Athlete♀ Sano',),
 ('Athlete♂ Senton',),
 ('Athlete♂ Taot',),
 ('Athlete♂ Tria',),
 ('Athlete♂ Varian',),
 ('Athlete♀ Ziale',),
 ('Bandana Guy Crace',),
 ('Bandana Guy Crag',),
 ('Bandana Guy Delav',),
 ('Bandana Guy Feek',),
 ('Bandana Guy Kaler',),
 ('Bandana Guy Kitel',),
 ('Bandana Guy Norel',),
 ('Bandana Guy Omak',),
 ('Bandana Guy Roblin',),
 ('Bandana Guy Venez',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Rita',),
 ('Beauty Rita',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Bird Keeper Adam',),
 ('Bird Keeper Adam',),
 ('Bird Keeper Matt',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Blackbelt Nick',),
 ('Blackbelt Nick',),
 ('Blackbelt Yang',),
 ('Blackbelt Yang',),
 ('Boarder Alvin',),
 ('Boarder Alvin',),
 ('Boarder Claude',),
 ('Boarder Claude',),
 ('Boarder Claude',),
 ('Bodybuilder♀ Banber',),
 ('Bodybuilder♂ Bergin',),
 ('Bodybuilder♂ Chiod',),
 ('Bodybuilder♀ Eldora',),
 ('Bodybuilder♀ Felmon',),
 ('Bodybuilder♂ Foalck',),
 ('Bodybuilder♀ Glya',),
 ('Bodybuilder♀ Helmin',),
 ('Bodybuilder♂ Lazko',),
 ('Bodybuilder♀ Lunda',),
 ('Bodybuilder♂ Mengel',),
 ('Bodybuilder♂ Rapoz',),
 ('Bodybuilder♂ Rawles',),
 ('Bodybuilder♀ Rogen',),
 ('Bodybuilder♂ Seet',),
 ('Bodybuilder♀ Tiana',),
 ('Bodybuilder♀ Velis',),
 ('Bodybuilder♀ Yagon',),
 ('Bodybuilder♂ Zicko',),
 ('Bodybuilder♂ Solog',),
 ('Bug Catcher Lyle',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Catcher Chaz',),
 ('Bug Catcher Chaz',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Jr.♂',),
 ('Camper Cole',),
 ('Camper Grant',),
 ('Camper Grant',),
 ('Casual Guy Makel',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Chaser♂ Bano',),
 ('Chaser♀ Busen',),
 ('Chaser♂ Chotle',),
 ('Chaser♂ Defren',),
 ('Chaser♀ Ethior',),
 ('Chaser♂ Faul',),
 ('Chaser♀ Gucio',),
 ('Chaser♂ Klame',),
 ('Chaser♂ Krigon',),
 ('Chaser♂ Mandev',),
 ('Chaser♂ Renfar',),
 ('Chaser♂ Slaben',),
 ('Chaser♂ Daks',),
 ('Chaser♀ Navu',),
 ('Chaser♀ Pixen',),
 ('Cipher Admin Ardos',),
 ('Cipher Admin Ardos',),
 ('Cipher Admin Eldes',),
 ('Cipher Admin Eldes',),
 ('Cipher Admin Gorigan',),
 ('Cipher Admin Gorigan',),
 ('Cipher Admin Snattle',),
 ('Cipher Admin Snattle',),
 ('Cipher Admin Lovrina',),
 ('Cipher Peon♂ Greesix',),
 ('Cipher Peon♂ Jargo',),
 ('Collector Brady',),
 ('Colosseum Leader Taylor',),
 ('Colosseum Leader Rosie',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Dusty',),
 ('Colosseum Leader Taylor',),
 ('Colosseum Leader Rosie',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Dusty',),
 ('Cool Beauty   Larissa',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cool♀',),
 ('Cool♀',),
 ('Cool♂',),
 ('Cool♂',),
 ('Cooltrainer♀ Becky',),
 ('Cooltrainer♂ Conner',),
 ('Cooltrainer♀ Floria',),
 ('Cooltrainer♀ Gloria',),
 ('Cooltrainer♀ Gloria',),
 ('Cooltrainer♂ Marty',),
 ('Cooltrainer♂ Marty',),
 ('Cooltrainer♂ Vince',),
 ('Cooltrainer♂ Vince',),
 ('Cooltrainer♀ Atilo',),
 ('Cooltrainer♂ Berki',),
 ('Cooltrainer♂ Cruik',),
 ('Cooltrainer♂ Dazon',),
 ('Cooltrainer♂ Desid',),
 ('Cooltrainer♀ Detta',),
 ('Cooltrainer♂ Dillot',),
 ('Cooltrainer♂ Farfin',),
 ('Cooltrainer♂ Forgon',),
 ('Cooltrainer♀ Gilly',),
 ('Cooltrainer♀ Gosney',),
 ('Cooltrainer♂ Hebel',),
 ('Cooltrainer♀ Levens',),
 ('Cooltrainer♀ Moden',),
 ('Cooltrainer♂ Morfon',),
 ('Cooltrainer♂ Moril',),
 ('Cooltrainer♀ Rask',),
 ('Cooltrainer♀ Rateis',),
 ('Cooltrainer♀ Rosno',),
 ('Cooltrianer♂ Shadd',),
 ('Cooltrainer♀ Tynan',),
 ('Cooltrianer♂ Vanhub',),
 ('Cooltrainer♀ Veron',),
 ('Cooltrainer♀ Zoel',),
 ('Cooltrainer♀ Ebson',),
 ('Cooltrainer♂ Klept',),
 ('Area Leader Axley',),
 ('Area Leader Cryal',),
 ('Area Leader Dessa',),
 ('Area Leader Erben',),
 ('Area Leader Glydin',),
 ('Area Leader Leven',),
 ('Area Leader Slewis',),
 ('Area Leader Vannos',),
 ('Area Leader Vario',),
 ('Area Leader Altor',),
 ('Area Leader Atrice',),
 ('Area Leader Elion',),
 ('Area Leader Konaik',),
 ('Area Leader Kucher',),
 ('Area Leader Langot',),
 ('Area Leader Mortac',),
 ('Area Leader Neblek',),
 ('Area Leader Vernice',),
 ('Athlete♀ Aleja',),
 ('Athlete♂ Busik',),
 ('Athlete♂ Deron',),
 ('Athlete♀ Dilasi',),
 ('Athlete♂ Gatik',),
 ('Athlete♂ Gulor',),
 ('Athlete♀ Kimber',),
 ('Athlete♂ Latrin',),
 ('Athlete♀ Mazzel',),
 ('Athlete♂ Menzon',),
 ('Athlete♂ Naga',),
 ('Athlete♀ Nomol',),
 ('Athlete♀ Pasha',),
 ('Athlete♀ Sano',),
 ('Athlete♂ Senton',),
 ('Athlete♂ Taot',),
 ('Athlete♂ Tria',),
 ('Athlete♂ Varian',),
 ('Athlete♀ Ziale',),
 ('Bandana Guy Crace',),
 ('Bandana Guy Crag',),
 ('Bandana Guy Delav',),
 ('Bandana Guy Feek',),
 ('Bandana Guy Kaler',),
 ('Bandana Guy Kitel',),
 ('Bandana Guy Norel',),
 ('Bandana Guy Omak',),
 ('Bandana Guy Roblin',),
 ('Bandana Guy Venez',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Battle Chatelaine Dana',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Alissa',),
 ('Beauty Rita',),
 ('Beauty Rita',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Biker Dillon',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Birdboy',),
 ('Bird Keeper Adam',),
 ('Bird Keeper Adam',),
 ('Bird Keeper Matt',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Judoboy',),
 ('Blackbelt Nick',),
 ('Blackbelt Nick',),
 ('Blackbelt Yang',),
 ('Blackbelt Yang',),
 ('Boarder Alvin',),
 ('Boarder Alvin',),
 ('Boarder Claude',),
 ('Boarder Claude',),
 ('Boarder Claude',),
 ('Bodybuilder♀ Banber',),
 ('Bodybuilder♂ Bergin',),
 ('Bodybuilder♂ Chiod',),
 ('Bodybuilder♀ Eldora',),
 ('Bodybuilder♀ Felmon',),
 ('Bodybuilder♂ Foalck',),
 ('Bodybuilder♀ Glya',),
 ('Bodybuilder♀ Helmin',),
 ('Bodybuilder♂ Lazko',),
 ('Bodybuilder♀ Lunda',),
 ('Bodybuilder♂ Mengel',),
 ('Bodybuilder♂ Rapoz',),
 ('Bodybuilder♂ Rawles',),
 ('Bodybuilder♀ Rogen',),
 ('Bodybuilder♂ Seet',),
 ('Bodybuilder♀ Tiana',),
 ('Bodybuilder♀ Velis',),
 ('Bodybuilder♀ Yagon',),
 ('Bodybuilder♂ Zicko',),
 ('Bodybuilder♂ Solog',),
 ('Bug Catcher Lyle',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Boy',),
 ('Bug Catcher Chaz',),
 ('Bug Catcher Chaz',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Bug Catcher Nelson',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Burglar Jensen',),
 ('Jr.♂',),
 ('Camper Cole',),
 ('Camper Grant',),
 ('Camper Grant',),
 ('Casual Guy Makel',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Medium',),
 ('Chaser♂ Bano',),
 ('Chaser♀ Busen',),
 ('Chaser♂ Chotle',),
 ('Chaser♂ Defren',),
 ('Chaser♀ Ethior',),
 ('Chaser♂ Faul',),
 ('Chaser♀ Gucio',),
 ('Chaser♂ Klame',),
 ('Chaser♂ Krigon',),
 ('Chaser♂ Mandev',),
 ('Chaser♂ Renfar',),
 ('Chaser♂ Slaben',),
 ('Chaser♂ Daks',),
 ('Chaser♀ Navu',),
 ('Chaser♀ Pixen',),
 ('Cipher Admin Ardos',),
 ('Cipher Admin Ardos',),
 ('Cipher Admin Eldes',),
 ('Cipher Admin Eldes',),
 ('Cipher Admin Gorigan',),
 ('Cipher Admin Gorigan',),
 ('Cipher Admin Snattle',),
 ('Cipher Admin Snattle',),
 ('Cipher Admin Lovrina',),
 ('Cipher Peon♂ Greesix',),
 ('Cipher Peon♂ Jargo',),
 ('Collector Brady',),
 ('Colosseum Leader Taylor',),
 ('Colosseum Leader Rosie',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Dusty',),
 ('Colosseum Leader Taylor',),
 ('Colosseum Leader Rosie',),
 ('Colosseum Leader Voldon',),
 ('Colosseum Leader Terrell',),
 ('Colosseum Leader Dusty',),
 ('Cool Beauty   Larissa',),
 ('Mr. Fix',),
 ('Mr. Fix',),
 ('Rocket Executive ♂',),
 ('Executive Petrel',),
 ('Rocket Executive ♀',),
 ('Rocket Executive ♀',),
 ('Rocket Executive ♂',),
 ('Rocket Executive ♂',),
 ('Firebreather Cliff',),
 ('Firebreather Cliff',),
 ('Firebreather Cliff',),
 ('Firebreather Cliff',),
 ('Fisherman',),
 ('Fisherman Ronald',),
 ('Fisherman Ronald',),
 ('Fisherman Wade',),
 ('Fisherman Wade',),
 ('Fisherman Andrew',),
 ('Fisherman Andrew',),
 ('Fisherman Kyler',),
 ('Fisherman Mick',),
 ('Fisherman Mack',),
 ('Fisherman Murray',),
 ('Fisher',),
 ('Fisher',),
 ('Fisher',),
 ('Fisher',),
 ('Fisherman Chase',),
 ('Fisherman Chase',),
 ('Fun Old Man Aikon',),
 ('Fun Old Man Berlo',),
 ('Fun Old Man Freyer',),
 ('Fun Old Man Grund',),
 ('Fun Old Man Hoglo',),
 ('Fun Old Man Kelvor',),
 ('Fun Old Man Orsak',),
 ('Fun Old Man Radle',),
 ('Fun Old Man Sciet',),
 ('Fun Old Man Wogort',),
 ('Fun Old Man Dargs',),
 ('Fun Old Man Rekix',),
 ('Future Girl Karla',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Old Man',),
 ('Girl In Love  Grace',),
 ('Glasses Man Acron',),
 ('Glasses Man Bayel',),
 ('Glasses Man Boren',),
 ('Glasses Man Dunor',),
 ('Glasses Man Eldan',),
 ('Glasses Man Lamag',),
 ('Glasses Man Lopar',),
 ('Glasses Man Omat',),
 ('Glasses Man Omarl',),
 ('Glasses Man Rood',),
 ('Guy Ardo',),
 ('Guy Baben',),
 ('Guy Botken',),
 ('Guy Deats',),
 ('Guy Foler',),
 ('Guy Ghols',),
 ('Guy Klem',),
 ('Guy Maton',),
 ('Guy Votil',),
 ('Guy Wiler',),
 ('Hardheaded Girl  Linda',),
 ('Hiker',),
 ('Hiker Chester',),
 ('Hiker Chester',),
 ('Hiker Chester',),
 ('Hiker Chester',),
 ('Hiking Girl   Annie',),
 ('Hunter♀ Alene',),
 ('Hunter♂ Arek',),
 ('Hunter♂ Basor',),
 ('Hunter♀ Bigon',),
 ('Hunter♀ Bolza',),
 ('Hunter♀ Cewan',),
 ('Hunter♂ Corvin',),
 ('Hunter♂ Girod',),
 ('Hunter♂ Gohn',),
 ('Hunter♂ Golog',),
 ('Hunter♂ Hasmen',),
 ('Hunter♂ Holso',),
 ('Hunter♂ Kolot',),
 ('Hunter♀ Ladin',),
 ('Hunter♀ Lisan',),
 ('Hunter♀ Milag',),
 ('Hunter♂ Parel',),
 ('Hunter♀ Procio',),
 ('Hunter♀ Rina',),
 ('Hunter♀ Sason',),
 ('Hunter♂ Spez',),
 ('Hunter♀ Zelmo',),
 ('Hunter♂ Greel',),
 ('Icy Guy  Cody',),
 ('Idol Grace',),
 ("Joe's Groupie   Kaitlyn",),
 ('Juggler',),
 ('Juggler',),
 ('Juggler',),
 ('Juggler',),
 ('Juggler',),
 ('Juggler',),
 ('Juggler Ferris',),
 ('Junior Representative Ichi-Ichi',),
 ('Kruger Family   Jonathan',),
 ('Kruger Family   Lonnie',),
 ('Lady Brena',),
 ('Lady Deasy',),
 ('Lady Denslon',),
 ('Lady Kylet',),
 ('Lady Nemi',),
 ('Lady Rene',),
 ('Lady Sanol',),
 ('Lady Stouner',),
 ('Lady Sturk',),
 ('Lady Talmen',),
 ('Lady Zolla',),
 ('Lady in Suit Amell',),
 ('Lady in Suit Grat',),
 ('Lady in Suit Isette',),
 ('Lady in Suit Jodin',),
 ('Lady in Suit Oatley',),
 ('Lady in Suit Secort',),
 ('Lass',),
 ('Lass',),
 ('Lass',),
 ('Lass',),
 ('Lass Lois',),
 ('Lass Lois',),
 ('Lass Nancy',),
 ('Lass Tammy',),
 ('Lass Terry',),
 ('Lass Terry',),
 ('Leader-in-Training♂ Marcel',),
 ('Leader-in-Training♂ Patrick',),
 ('Leader-in-Training♀ Dominique',),
 ('Lone Wolf   Graham',),
 ('Lone Wolf   Robert',),
 ('Maid Tammy',),
 ('Master Class Cortney',),
 ('Master Class Erica',),
 ('Master Class Eva',),
 ('Master Class Jackson',),
 ('Master Class Jaden',),
 ('Master Class Kaden',),
 ('Master Class Kerry',),
 ('Master Class Kinsey',),
 ('Master Class Lincoln',),
 ('Master Class Lyle',),
 ('Master Class Miriam',),
 ('Master Class Preston',),
 ('Master Class Ryan',),
 ('Master Class Tate',),
 ('Master Class Tiffany',),
 ('Fun Old Lady Desor',),
 ('Fun Old Lady Eskola',),
 ('Fun Old Lady Flegal',),
 ('Fun Old Lady Gohon',),
 ('Fun Old Lady Grenay',),
 ('Fun Old Lady Gularte',),
 ('Fun Old Lady Karden',),
 ('Fun Old Lady Ludum',),
 ('Fun Old Lady Myog',),
 ('Fun Old Lady Otsbo',),
 ('Fun Old Lady Perstin',),
 ('Matron Naono',),
 ('Mature Couple  Carissa',),
 ('Mature Couple  Ian',),
 ('Medium Holly',),
 ('Medium Holly',),
 ('Movie Star ♂ Brycen',),
 ('Mt.BtlMaster Somek',),
 ('Mt.BtlMaster Infin(Single Battle)',),
 ('Mt.BtlMaster Inity(Double Battle)',),
 ('Mt BtlMaster Battlus',),
 ('Myth Trainer Infin',),
 ('Myth Trainer Inity',),
 ('Myth Trainer Eagun',),
 ('Navigator Lestor',),
 ('Newscaster Riesko',),
 ('Newscaster Sclim',),
 ('Newscaster Sivil',),
 ('Ordinary Guy  Alec',),
 ('Passionate Rider  Ruben',),
 ('Passionate Rider  Hannah',),
 ('Passionate Rider  Norman',),
 ('Gambler',),
 ('Gambler',),
 ('Gambler',),
 ('Gambler',),
 ('Gambler',),
 ('Gambler',),
 ('Picnic Girl  Elena',),
 ('Jr.♀',),
 ('Jr.♀',),
 ('Jr.♀',),
 ('Picnicker Cyndy',),
 ('Picnicker Stacy',),
 ('Picnicker Stacy',),
 ('Pikachu Fan  Damon',),
 ('Pikachu Fan  Tasha',),
 ('Pikachu Fan  Stewart',),
 ('Poison Tongue Boy   Curtis',),
 ('Pokéfan♂ Joshua',),
 ('Pokéfan♂ Colton',),
 ('Pokéfan♂ Colton',),
 ('Pokéfan♂ Joshua',),
 ('Pokéfan♂ Baxter',),
 ('Pokéfan♂ Baxter',),
 ('Pokéfan♂ Baxter',),
 ('Pokéfan♂ Baxter',),
 ('Pokéfan♀ Carmen',),
 ('Pokéfan♀ Carmen',),
 ('Pokéfan♀ Carmen',),
 ('Pokéfan♀ Janet',),
 ('Pokéfan♀ Janet',),
 ('Pokéfan♂ Rex',),
 ('Pokéfan♂ Rex',),
 ('PokéManiac Joseph',),
 ('PokéManiac Pedro',),
 ('PokéManiac Pedro',),
 ('PokéManiac Pedro',),
 ('PokéManiac Pedro',),
 ('Psychic',),
 ('Psychic',),
 ('Psychic',),
 ('Psychic',),
 ('Psychic',),
 ('Psychic',),
 ('Psychic Mason',),
 ('Psychic Mason',),
 ('Psychic Mason',),
 ('Psychic Mason',),
 ('Rich Boy Basto',),
 ('Rich Boy Benit',),
 ('Rich Boy Brot',),
 ('Rich Boy Denc',),
 ('Rich Boy Guyit',),
 ('Rich Boy Marcon',),
 ('Rich Boy Perc',),
 ('Rich Boy Puros',),
 ('Rich Boy Roex',),
 ('Rich Boy Sainz',),
 ('Rich Boy Symin',),
 ('Rich Boy Tark',),
 ('Rich Boy Venak',),
 ('Rider♂ Finson',),
 ('Rider♂ Fokil',),
 ('Rider♀ Jorner',),
 ('Rider♀ Kibbe',),
 ('Rider♀ Kimery',),
 ('Rider♀ Kou',),
 ('Rider♀ Laret',),
 ('Rider♂ Lohon',),
 ('Rider♀ Maloo',),
 ('Rider♀ Marley',),
 ('Rider♀ Mayme',),
 ('Rider♂ Orden',),
 ('Rider♀ Porta',),
 ('Rider♀ Pulink',),
 ('Rider♂ Rebin',),
 ('Rider♂ Rogin',),
 ('Rider♀ Stefet',),
 ('Rider♂ Trank',),
 ('Rider♂ Wendo',),
 ('Rider♂ Veston',),
 ('Rider♀ Vlum',),
 ('Rider♀ Zalla',),
 ('Rider♂ Herlam',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Rocker',),
 ('Roller Boy Aich',),
 ('Roller Boy Bidix',),
 ('Roller Boy Garlow',),
 ('Roller Boy Gars',),
 ('Roller Boy Hites',),
 ('Roller Boy Peres',),
 ('Roller Boy Polet',),
 ('Roller Boy Shail',),
 ('Roller Boy Tary',),
 ('Roller Boy Tobit',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Cueball',),
 ('Sage Chen',),
 ('Sage Chen',),
 ('Sage Chen',),
 ('Sage Chen',),
 ('Sage Ty',),
 ('Sage Ty',),
 ('Sailor',),
 ('Sailor',),
 ('Sailor',),
 ('Sailor Jebol',),
 ('School Kid♀ Serena',),
 ('Schoolboy Carson',),
 ('Schoolboy Clark',),
 ('Schoolboy Clark',),
 ('Schoolboy Nolan',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Lab Man',),
 ('Scientist Craig',),
 ('Scientist Craig',),
 ('Researcher Doimo',),
 ('Researcher Doton',),
 ('Researcher Durel',),
 ('Researcher Hildon',),
 ('Researcher Kukla',),
 ('Researcher Messa',),
 ('Researcher Nanot',),
 ('Researcher Platen',),
 ('Researcher Raburn',),
 ('Researcher Reman',),
 ('Researcher Limar',),
 ('Researcher Newin',),
 ('Shady Guy Wes',),
 ('Sim Trainer Hiplog',),
 ('Sim Trainer Logan',),
 ('Skier Carol',),
 ('Skier Carol',),
 ('Skier Kathy',),
 ('St.Performer Erion',),
 ('St.Performer Lirel',),
 ('St.Performer Lonen',),
 ('St.Performer Macik',),
 ('St.Performer Mino',),
 ('St.Performer Scherla',),
 ('St.Performer Sido',),
 ('St.Performer Sirko',),
 ('St.Performer Volivia',),
 ('Stubborn Boy  David',),
 ('Nerd',),
 ('Nerd',),
 ('Nerd',),
 ('Nerd',),
 ('Super Nerd Clifford',),
 ('Super Nerd Clifford',),
 ('Super Nerd Clifford',),
 ('Super Nerd Clifford',),
 ('Super Nerd Melvin',),
 ('Supertrainer♀ Avos',),
 ('Supertrainer♂ Buril',),
 ('Supertrainer♀ Charl',),
 ('Supertrainer♂ Codel',),
 ('Supertrainer♂ Gally',),
 ('Supertrainer♀ Garvon',),
 ('Supertrainer♀ Grang',),
 ('Supertrainer♂ Gravet',),
 ('Supertrainer♀ Holoh',),
 ('Supertrainer♂ Hufnak',),
 ('Supertrainer♀ Huron',),
 ('Supertrainer♂ Kauson',),
 ('Supertrainer♂ Lagin',),
 ('Supertrainer♂ Okamoo',),
 ('Supertrainer♀ Saya',),
 ('Supertrainer♂ Shoo',),
 ('Supertrainer♂ Shun',),
 ('Supertrainer♀ Tangut',),
 ('Supertrainer♂ Tardel',),
 ('Supertrainer♀ Lest',),
 ('Supertrainer♀ Libal',),
 ('Supertrainer♀ Nimblis',),
 ('Swimmer♂ George',),
 ('Swimmer♂ George',),
 ('Swimmer',),
 ('Swimmer',),
 ('Swimmer',),
 ('Swimmer',),
 ('Swimmer♂ Bruce',),
 ('Swimmer♂ Bruce',),
 ('Swimmer♂ Bruce',),
 ('Swimmer♂ Bruce',),
 ('Swimmer♀ Cora',),
 ('Swimmer♀ Cora',),

Part 4 - Airbnb

Q1

In [ ]:
%%sql
select host_id,host_name,max(listing)
from
(select host_id,host_name,count(*) as listing
from AB_NYC_2019
where neighbourhood_group='Manhattan'
group by host_id)

 * sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[(219517861, 'Sonder (NYC)', 327)]

Q2

In [ ]:
%%sql
select neighbourhood
from AB_NYC_2019
where room_type='Private room' and (price=(select min(price) from AB_NYC_2019) or price=(select max(price) from AB_NYC_2019))
group by neighbourhood

 * sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Astoria',),
 ('Bedford-Stuyvesant',),
 ('Bushwick',),
 ('East Morrisania',),
 ('Greenpoint',)]

Q3

In [ ]:
%%sql
select neighbourhood,count(*) as 'number of apartments',max(price),min(price),avg(price)
from AB_NYC_2019
group by neighbourhood
order by count(*) desc

 * sqlite:////content/Airbnb.db
   sqlite:////content/pokemon.db
   sqlite:////content/titanic.db
Done.

[('Williamsburg', 3920, 4500, 0, 143.80280612244897),
 ('Bedford-Stuyvesant', 3714, 5000, 0, 107.67824448034465),
 ('Harlem', 2658, 5000, 10, 118.97404063205417),
 ('Bushwick', 2465, 2000, 0, 84.80040567951319),
 ('Upper West Side', 1971, 10000, 10, 210.91831557584982),
 ("Hell's Kitchen", 1958, 4100, 10, 204.79417773237998),
 ('East Village', 1853, 3750, 10, 186.0831084727469),
 ('Upper East Side', 1798, 7703, 10, 188.94827586206895),
 ('Crown Heights', 1564, 2500, 12, 112.480179028133),
 ('Midtown', 1545, 5100, 30, 282.7190938511327),
 ('East Harlem', 1117, 9999, 30, 133.1987466427932),
 ('Greenpoint', 1115, 10000, 0, 144.82242152466367),
 ('Chelsea', 1113, 6800, 12, 249.73854447439354),
 ('Lower East Side', 911, 9999, 29, 186.31284302963775),
 ('Astoria', 900, 10000, 25, 117.18777777777778),
 ('Washington Heights', 899, 1000, 16, 89.6106785317019),
 ('West Village', 768, 4000, 50, 267.6822916666667),
 ('Financial District', 744, 3000, 12, 225.49059139784947),
 ('Flatbush', 621, 1100, 20, 92.21256038647343),
 ('Clinton Hill', 572, 8000, 35, 181.89335664335664),
 ('Long Island City', 537, 2000, 30, 127.46554934823091),
 ('Prospect-Lefferts Gardens', 535, 2545, 22, 110.40186915887851),
 ('Park Slope', 506, 2626, 30, 176.31225296442688),
 ('East Flatbush', 500, 7500, 15, 104.222),
 ('Fort Greene', 489, 1200, 25, 151.37423312883436),
 ('Murray Hill', 485, 2000, 0, 220.95876288659792),
 ('Kips Bay', 470, 2750, 10, 202.40851063829788),
 ('Flushing', 426, 1500, 15, 93.51408450704226),
 ('Ridgewood', 423, 375, 20, 77.18439716312056),
 ('Greenwich Village', 392, 6000, 43, 263.40561224489795),
 ('Sunset Park', 390, 2000, 10, 113.04102564102564),
 ('Chinatown', 368, 1500, 41, 161.49728260869566),
 ('Sunnyside', 363, 600, 12, 84.86501377410468),
 ('SoHo', 358, 3000, 10, 287.1033519553073),
 ('Prospect Heights', 357, 4000, 34, 173.37254901960785),
 ('Morningside Heights', 346, 1200, 30, 114.78323699421965),
 ('Gramercy', 338, 3000, 45, 222.75443786982248),
 ('Ditmars Steinway', 309, 600, 22, 95.02912621359224),
 ('Theater District', 288, 3000, 40, 248.01388888888889),
 ('South Slope', 284, 500, 40, 146.72535211267606),
 ('Nolita', 253, 5000, 20, 230.13833992094862),
 ('Inwood', 252, 359, 22, 88.89682539682539),
 ('Gowanus', 247, 1333, 35, 158.80161943319837),
 ('Elmhurst', 237, 443, 15, 80.45991561181435),
 ('Woodside', 235, 500, 28, 85.09787234042552),
 ('Carroll Gardens', 233, 1395, 40, 175.91416309012877),
 ('Jamaica', 231, 1000, 10, 95.77056277056278),
 ('East New York', 218, 300, 25, 85.42660550458716),
 ('Jackson Heights', 186, 260, 23, 80.89784946236558),
 ('East Elmhurst', 185, 700, 16, 81.18378378378378),
 ('Boerum Hill', 177, 1000, 46, 176.135593220339),
 ('Tribeca', 177, 8500, 60, 490.638418079096),
 ('Kensington', 175, 525, 24, 92.88571428571429),
 ('Sheepshead Bay', 164, 2000, 20, 105.77439024390245),
 ('Windsor Terrace', 157, 450, 38, 138.9936305732484),
 ('Brooklyn Heights', 154, 1500, 45, 209.06493506493507),
 ('Canarsie', 147, 600, 25, 104.36734693877551),
 ('Forest Hills', 144, 2350, 16, 121.625),
 ('Bay Ridge', 141, 4200, 18, 144.43262411347519),
 ('Borough Park', 136, 300, 20, 63.06617647058823),
 ('Cypress Hills', 135, 5000, 19, 128.9037037037037),
 ('Little Italy', 121, 5250, 41, 222.06611570247935),
 ('Maspeth', 110, 245, 11, 83.64545454545454),
 ('Midwood', 109, 250, 20, 80.33944954128441),
 ('Rego Park', 106, 300, 21, 83.87735849056604),
 ('Cobble Hill', 99, 1750, 59, 211.92929292929293),
 ('Richmond Hill', 94, 300, 28, 87.11702127659575),
 ('Woodhaven', 88, 250, 10, 67.17045454545455),
 ('Springfield Gardens', 85, 300, 40, 94.23529411764706),
 ('Downtown Brooklyn', 83, 650, 39, 150.34939759036143),
 ('Flatlands', 83, 1700, 22, 126.43373493975903),
 ('Flatiron District', 80, 2000, 65, 341.925),
 ('Red Hook', 79, 750, 30, 143.45569620253164),
 ('NoHo', 78, 1795, 75, 295.71794871794873),
 ('Arverne', 77, 1500, 35, 171.7792207792208),
 ('Roosevelt Island', 77, 1400, 30, 113.25974025974025),
 ('St. Albans', 76, 600, 25, 100.82894736842105),
 ('Bensonhurst', 75, 200, 15, 75.78666666666666),
 ('Brighton Beach', 75, 3000, 30, 131.93333333333334),
 ('Two Bridges', 72, 320, 35, 127.06944444444444),
 ('Battery Park City', 70, 7500, 55, 367.5571428571429),
 ('Kingsbridge', 70, 399, 27, 77.92857142857143),
 ('Gravesend', 68, 300, 20, 79.01470588235294),
 ('Corona', 64, 359, 23, 59.171875),
 ('Fordham', 63, 223, 21, 69.44444444444444),
 ('Longwood', 62, 680, 27, 91.91935483870968),
 ('Ozone Park', 62, 200, 25, 85.2741935483871),
 ('Brownsville', 61, 300, 28, 76.45901639344262),
 ('Mott Haven', 60, 500, 35, 88.91666666666667),
 ('Queens Village', 60, 320, 25, 83.93333333333334),
 ('Rosedale', 59, 350, 22, 76.69491525423729),
 ('Briarwood', 56, 1000, 30, 105.875),
 ('Rockaway Beach', 56, 545, 49, 132.17857142857142),
 ('Fort Hamilton', 55, 200, 20, 93.81818181818181),
 ('Glendale', 54, 299, 25, 90.79629629629629),
 ('Civic Center', 52, 950, 50, 191.94230769230768),
 ('Concourse', 50, 250, 35, 86.18),
 ('Wakefield', 50, 309, 28, 85.58),
 ('St. George', 48, 1000, 29, 118.14583333333333),
 ('Port Morris', 46, 220, 28, 79.8913043478261),
 ('Allerton', 42, 450, 33, 87.5952380952381),
 ('Columbia St', 42, 1080, 55, 162.95238095238096),
 ('Tompkinsville', 42, 245, 30, 76.19047619047619),
 ('South Ozone Park', 40, 400, 29, 82.4),
 ('Williamsbridge', 40, 500, 25, 96.75),
 ('Bayside', 39, 2600, 30, 157.94871794871796),
 ('Parkchester', 39, 300, 25, 69.07692307692308),
 ('Stuyvesant Town', 37, 1500, 45, 169.1081081081081),
 ('DUMBO', 36, 400, 74, 196.30555555555554),
 ('Vinegar Hill', 34, 550, 46, 187.1764705882353),
 ('Concourse Village', 32, 159, 34, 73.78125),
 ('Fresh Meadows', 32, 375, 39, 99.5),
 ('Kew Gardens', 32, 219, 35, 88.375),
 ('Middle Village', 31, 265, 28, 109.58064516129032),
 ('Norwood', 31, 200, 26, 75.54838709677419),
 ('Far Rockaway', 29, 900, 35, 165.86206896551724),
 ('Claremont Village', 28, 390, 26, 87.46428571428571),
 ('Pelham Gardens', 28, 450, 20, 93.60714285714286),
 ('Highbridge', 27, 240, 10, 71.11111111111111),
 ('Stapleton', 27, 450, 34, 98.96296296296296),
 ('Cambria Heights', 26, 250, 31, 81.73076923076923),
 ('Concord', 26, 200, 29, 58.19230769230769),
 ('Kew Gardens Hills', 26, 399, 40, 112.3076923076923),
 ('Belmont', 24, 299, 24, 77.125),
 ('Throgs Neck', 24, 325, 40, 91.04166666666667),
 ('Arrochar', 21, 625, 32, 115.0),
 ('Clason Point', 21, 379, 40, 112.76190476190476),
 ('University Heights', 21, 175, 37, 69.57142857142857),
 ('Howard Beach', 20, 250, 40, 115.4),
 ('Mount Hope', 20, 250, 24, 77.5),
 ('Bronxdale', 19, 100, 25, 57.10526315789474),
 ('College Point', 19, 400, 44, 88.0),
 ('Jamaica Estates', 19, 750, 35, 182.94736842105263),
 ('Randall Manor', 19, 5000, 13, 336.0),
 ('City Island', 18, 1000, 29, 173.0),
 ('Hunts Point', 18, 150, 35, 50.5),
 ('Laurelton', 18, 254, 34, 95.33333333333333),
 ('Morrisania', 18, 225, 23, 83.44444444444444),
 ('West Brighton', 18, 200, 37, 80.55555555555556),
 ('Bath Beach', 17, 180, 33, 81.76470588235294),
 ('Bayswater', 17, 230, 45, 87.47058823529412),
 ('Coney Island', 17, 450, 25, 123.70588235294117),
 ('Morris Heights', 17, 240, 20, 76.94117647058823),
 ('Pelham Bay', 17, 299, 37, 105.0),
 ('Clifton', 15, 165, 40, 84.93333333333334),
 ('Morris Park', 15, 190, 29, 69.33333333333333),
 ('Soundview', 15, 103, 28, 53.46666666666667),
 ('Bellerose', 14, 240, 42, 99.35714285714286),
 ('Hollis', 14, 175, 50, 88.64285714285714),
 ('Navy Yard', 14, 295, 50, 151.64285714285714),
 ('Eastchester', 13, 475, 45, 141.69230769230768),
 ('Edenwald', 13, 149, 42, 82.0),
 ('Schuylerville', 13, 150, 20, 69.23076923076923),
 ('Dyker Heights', 12, 170, 30, 93.41666666666667),
 ('Fieldston', 12, 135, 49, 75.08333333333333),
 ('Marble Hill', 12, 274, 40, 89.16666666666667),
 ('Edgemere', 11, 200, 40, 94.72727272727273),
 ('Riverdale', 11, 2500, 49, 442.09090909090907),
 ('Tremont', 11, 150, 25, 51.54545454545455),
 ('Van Nest', 11, 425, 20, 113.81818181818181),
 ('Whitestone', 11, 400, 35, 107.54545454545455),
 ('Woodlawn', 11, 85, 29, 60.09090909090909),
 ('Bergen Beach', 10, 235, 49, 106.7),
 ('East Morrisania', 10, 200, 0, 85.0),
 ('Great Kills', 10, 235, 40, 100.6),
 ('Melrose', 10, 150, 42, 83.3),
 ('North Riverdale', 10, 150, 40, 79.9),
 ('Westchester Square', 10, 670, 28, 122.2),
 ('Castle Hill', 9, 128, 38, 63.0),
 ('Port Richmond', 9, 250, 40, 90.11111111111111),
 ('Belle Harbor', 8, 350, 85, 171.5),
 ('Douglaston', 8, 178, 40, 82.75),
 ('Jamaica Hills', 8, 325, 50, 132.125),
 ('Manhattan Beach', 8, 150, 45, 103.5),
 ('Mariners Harbor', 8, 200, 40, 94.625),
 ('New Springville', 8, 150, 43, 76.0),
 ('South Beach', 8, 275, 20, 89.25),
 ('Baychester', 7, 101, 53, 75.42857142857143),
 ('Dongan Hills', 7, 155, 37, 79.42857142857143),
 ('Grymes Hill', 7, 300, 89, 159.14285714285714),
 ('Rosebank', 7, 200, 55, 111.85714285714286),
 ('Sea Gate', 7, 1485, 71, 487.85714285714283),
 ('Shore Acres', 7, 300, 54, 152.71428571428572),
 ('Tottenville', 7, 299, 70, 144.85714285714286),
 ('Unionport', 7, 450, 60, 137.14285714285714),
 ('Bay Terrace', 6, 258, 32, 142.0),
 ("Bull's Head", 6, 80, 25, 47.333333333333336),
 ('Grant City', 6, 80, 29, 57.666666666666664),
 ('Midland Beach', 6, 115, 61, 91.83333333333333),
 ('Mount Eden', 6, 150, 25, 58.5),
 ('Emerson Hill', 5, 85, 49, 68.2),
 ('Little Neck', 5, 149, 32, 75.2),
 ('New Brighton', 5, 249, 40, 101.8),
 ('New Dorp Beach', 5, 109, 36, 57.4),
 ('Oakwood', 5, 130, 46, 81.2),
 ('Arden Heights', 4, 83, 41, 67.25),
 ('Castleton Corners', 4, 299, 45, 139.75),
 ('Holliswood', 4, 239, 79, 135.75),
 ('Mill Basin', 4, 299, 85, 179.75),
 ('Olinville', 4, 125, 25, 64.0),
 ("Prince's Bay", 4, 1250, 85, 409.5),
 ('Spuyten Duyvil', 4, 360, 60, 154.75),
 ('Todt Hill', 4, 429, 50, 169.0),
 ('Breezy Point', 3, 250, 195, 213.33333333333334),
 ('Eltingville', 3, 299, 56, 141.66666666666666),
 ('Graniteville', 3, 115, 20, 68.66666666666667),
 ('Huguenot', 3, 180, 75, 118.33333333333333),
 ('Neponsit', 3, 350, 200, 274.6666666666667),
 ('Bay Terrace, Staten Island', 2, 150, 55, 102.5),
 ('Co-op City', 2, 80, 75, 77.5),
 ('Howland Hook', 2, 100, 100, 100.0),
 ('Lighthouse Hill', 2, 200, 115, 157.5),
 ('Silver Lake', 2, 80, 60, 70.0),
 ('West Farms', 2, 165, 79, 122.0),
 ('Westerleigh', 2, 103, 40, 71.5),
 ('Fort Wadsworth', 1, 800, 800, 800.0),
 ('New Dorp', 1, 57, 57, 57.0),
 ('Richmondtown', 1, 78, 78, 78.0),
 ('Rossville', 1, 75, 75, 75.0),
 ('Willowbrook', 1, 249, 249, 249.0),
 ('Woodrow', 1, 700, 700, 700.0)]